### ISSUE TITLE
Authentication failed for iCloud notes

### ISSUE THREAD

**Issue by ghost** [nbenm/ImapNote2#12] opened 2015-11-26 06:35 UTC
I was wondering if maybe the ImapNotes2 doesn't support El Capitan's Notes?

I used my Gmail account to register iCloud, but when I tried to add this account in ImapNotes2, it failed.

![3 pic_hd](https://cloud.githubusercontent.com/assets/382763/11416718/5c9d7b8c-944b-11e5-9465-34cc3b85b851.jpg)

**Comment by ghost** [comment] 2015-11-27 02:00
After created a `@icloud.com` account, it still failed:(

**Comment by N0ury** [comment] 2015-11-27 10:05
Hi Le,

With an icloud.com account, it works like this:
- Accountname: free string without quotes nor double quotes
- Username : your iCloud username without the "@icloud.com" part. Sometimes you must add it, Apple isn't very clear
- Password : your iCloud password
- Server : imap.mail.me.com
- Security : SSL/TLS
- Port Number : 993
- Sync interval : any value you want. 15 minutes is good to avoid unnecessary requests (wifi ou 3G...) which are battery consumming
- Leave "Use Stickynotes" unchecked

Regards

Noury

**Comment by N0ury** [comment] 2016-02-29 10:34
Hi Le,

I'm closing this issue.
If it's needed, you can reopen it

Regards

Noury

**Closed as completed by N0ury** 2016-02-29 10:34 UTC

**Comment by SeriusNtentions** [comment] 2017-10-30 13:07
Hello I am trying to log into my icloud notes with my non rooted Android LG G3 on android 6.0 and my password ends with a ! I tried this method but I am still getting the same parser error

**Comment by kwhitefoot** [comment] 2017-10-31 07:05
@SeriusNtentions Can you try changing your password so that it has only letters and numbers and see if that helps?  Can you post a screenshot of the actual error?

**Comment by SeriusNtentions** [comment] 2017-10-31 12:41
The error message is "A0 BAD Parse Error" I do not want to change my password. If this app cannot work as is I will make due without syyncing my notes. Thanks for your help.

**Comment by kwhitefoot** [comment] 2017-10-31 12:50
@SeriusNtentions  I don't mean that you have to change it permanently.  Just change it to see if the problem is that the combination the app and the IMAP server don't work with your password.  Then change it back.


------ Unix is like a wigwam: no gates, no windows and an Apache inside.


________________________________

**Comment by neel** [comment] 2018-01-31 17:00
I am getting the same Error "A0 BAD Parse Error". I don't have a special character password. I have used my email address with or without @icloud.com

![screenshot_20180131-221753](https://user-images.githubusercontent.com/20411/35636119-2f499f94-06d6-11e8-931d-239998f21d90.png)
