### ISSUE TITLE
Notes created in ImapNote2 synced via Outlook.com are read only in Outlook 

### ISSUE THREAD

**Issue by Umma-2-gumma** [nbenm/ImapNote2#7] opened 2015-11-24 13:35 UTC
I am using Outlook.com preview (that provides Exchange capability) to sync my desktop Outlook notes to my iPad.

Outlook <- Outlook.com -> iPad

I hope to use ImapNote2 as a conduit to sync the same notes to my Android phone.

Here's the problem I am running into:
- notes created in Outlook sync fine to both iPad and IN2
- notes created on iPad sync fine to Outlook and IN2
- notes created in IN2 show up in Outlook as read only (with an envelope icon instead of note icon) and don't sync at all to iPad.

The workaround now is to manually copy & paste into a new note in Outlook. This however will not work if I am traveling and don't have my laptop with me.

**Comment by N0ury** [comment] 2015-12-20 10:33
Hi Umma-2-gumma,
I need some more informations.
I've tried to reproduce the problem but I can't.
- what outlook client do you use ? I have tried Office 2016 for Mac
- what account do you use? I have tried to configure an outlook.com account as an Exchange account, but this is not possible. With imap and smtp account, notes are in Notes folder but readonly. This is normal since imap doesn't permit modifications in emails. Notes are stored on an other tab.

Can you please tell me how to reproduce the case

Regards

Noury

**Comment by N0ury** [comment] 2016-02-29 10:37
Hi Umma-2-gumma,

I'm closing this issue.
You can reopen it if needed, but I need informations asked above to reproduce the case

Regards

Noury

**Closed as completed by N0ury** 2016-02-29 10:37 UTC
Labels: enhancement
