### ISSUE TITLE
Android 5.0 connection issue

### ISSUE THREAD

**Issue by sc68cal** [nbenm/ImapNote2#1] opened 2015-01-03 22:22 UTC
First off, this is a great app! Thanks for maintaining.

I have an LG phone with Android 4.4 and a Nexus 7 that has Android 5.0, and the Nexus 7 tablet shows a connection error when attempting to connect to my IMAP server. I'll look into how to get useful debugging.

**Comment by sc68cal** [comment] 2015-01-03 22:23
Looking at my IMAP server's logs, it does not appear that the app, when running on the Nexus 7 even initiates any network connections when I hit the login button in the application.

**Comment by N0ury** [comment] 2015-01-03 22:39
Hi sc68cal,

The app uses imaps (port 993, ssl connection) only.
I'm changing this to accept map (port 143), but it will take some time as related changes are going on too.

At this time the app can't work with untrusted certificates (ex self signed). But:
- you can get a trusted one for free at startssl
- you can import your certificate in your device

Among changes mentioned above, one is to accept untrusted certificates.

nb

**Comment by N0ury** [comment] 2015-01-04 08:13
Hi sc68cal,

A new version is available here (not still uploaded to Google Play).
You can use untrusted certificates. Useful if you use a self signed certificate.
Can you please tell me if your problem is solved

Regards

nb

**Comment by sc68cal** [comment] 2015-01-04 11:43
Hi,

The IMAP server I have only runs on port 993, and has a valid SSL certificate. I do not see the connection error issue when running on my Android 4.4 handset from LG, compared to my Nexus 7 running Android 5.0

**Comment by N0ury** [comment] 2015-01-04 12:18
Hi Sean,

> The IMAP server I have only runs on port 993, and has a valid SSL certificate. I do not see the connection error issue when running on my Android 4.4 handset from LG, compared to my Nexus 7 running Android 5.0

Can you provide me a test account on your server
You can reply by PM at nb(at)dagami.org

nb

**Comment by sc68cal** [comment] 2015-01-05 23:56
Sorry, I cannot.

**Comment by N0ury** [comment] 2015-01-10 09:00
I have tried it on an ASUS Transformer TF101 with Android 5.0.1, and everything is ok.
I cannot reproduce the problem.

**Comment by N0ury** [comment] 2015-04-30 13:54
I'm closing this issue. If you have yet any problem and the mean to reproduce it let me know.

**Closed as completed by N0ury** 2015-04-30 13:54 UTC
